! ------------------------------------------------------------------------------
! ROFI Color theme
! User: Jaxson Van Doorn
! Copyright: Jaxson Van Doorn
! ------------------------------------------------------------------------------
rofi.color-enabled: true
rofi.color-window: #1b182c, #1b182c, #1b182c
rofi.color-normal: #1b182c, #ffffff, #1b182c, #906cff, #ffffff
rofi.color-active: #1b182c, #ffffff, #1b182c, #906cff, #ffffff
rofi.color-urgent: #1b182c, #ff1844, #1b182c, #906cff, #ff1844

