#!/bin/bash

# Execute Commands on Startup Only on my Dell Laptop
if [[ $(hostname -s) = Jaxson-Debian ]]; then

    # Calibrate Monitor
    xgamma -rgamma 0.94 -ggamma 0.93 -bgamma 0.98

    # Setup Second Display
    xrandr --setprovideroutputsource 1 0
    xrandr --auto --output DVI-I-1-1 --mode 1920x1080 --left-of eDP-1
    DISPLAY=:0.0 feh --bg-scale ~/Pictures/bg.jpg

    # Start Compton
    compton -b --config ~/.config/compton/compton.conf
    volume mute
elif [[ $(whoami) = jaxson-work ]]; then
    slack
else
    discord
    steam
fi
