#!/bin/bash

function song {
    spotify=$(spotifycli --status)
    if [ "$spotify" == "" ]; then
        echo 0
    else
        echo 1
    fi
}

song=$(song)
if [ $song -eq 1 ]; then
    spotifycli --pause
fi
i3lock-next '' '' 1
if [ $song -eq 1 ]; then
    spotifycli --play
fi
