#!/usr/bin/env bash

function show_help {
  echo "usage: music [option]"
  echo ""
  echo "CLI interface for Rhythmbox and Spotify"
  echo ""
  echo "options: "
  echo "  --status      show current song"
  echo "  --i3status    show current song with color and icon for i3"
  echo "  --swaystatus  show current song with color and icon for sway"
  echo "  --playpause   toggle play status of current song"
  echo "  --help        show help"
}

function play_pause {
  PLAYER=$1
  if [ "$PLAYER" == 'rhythmbox' ]; then
    rhythmbox-client --play-pause
  else
    spotifycli --playpause
  fi
}

function playing {
  PLAYER=$1
  if [ "$PLAYER" == 'rhythmbox' ]; then
    STATUS=$(rhythmbox-client --print-playing)
  else
    STATUS=$(spotifycli --status 2> /dev/null)
  fi
  echo $STATUS
}


function status {
  PLAYER=$1
  if [ "$PLAYER" == 'rhythmbox' ]; then
    STATUS=$(rhythmbox_status)
  else
    STATUS=$(spotify_status)
  fi
  echo $STATUS
}

function is_playing {
  STATUS=$(status $1)
  if [ "$STATUS" == "" ]; then
    echo 0
  else
    echo 1
  fi
}

function is_running {
  STATUS=$(status $1)
  if [ "$STATUS" == "" ]; then
    echo 1
  else
    echo 0
  fi
}

function is_active {
  STATUS=$(status $1)
  if [ "$STATUS" == "" ] || [ "$STATUS" == "" ]; then
    echo 1
  else
    echo 0
  fi
}

function rhythmbox_status {
  STOPED="(<'Stopped'>,)"
  PLAYING="(<'Playing'>,)"
  PAUSED="(<'Paused'>,)"
  # From https://askubuntu.com/questions/793647/how-to-determine-from-the-command-line-whether-rhythmbox-is-playing
  OUT=$(gdbus call \
       --session \
       --dest org.mpris.MediaPlayer2.rhythmbox \
       --object-path /org/mpris/MediaPlayer2 \
       --method org.freedesktop.DBus.Properties.Get \
           org.mpris.MediaPlayer2.Player PlaybackStatus 2> /dev/null)
  STATUS=$?
  if [ "$STATUS" != 0 ]; then
    echo ''
  else
    if [ "$OUT" == "$STOPED" ]; then
      echo ''
    elif [ "$OUT" == "$PLAYING" ]; then
      echo ''
    elif [ "$OUT" == "$PAUSED" ]; then
      echo ''
    fi
  fi
}

function spotify_status {
  CLOSED='Spotify is off '
  OUT=$(spotifycli --playbackstatus 2> /dev/null)
  STATUS=$?
  if [ "$STATUS" != 0 ]; then
    echo ''
  elif [ "$OUT" == "▶" ]; then
    echo ''
  else
    echo ''
  fi
}

RHYTHMBOX_RUNNING=$(is_running "rhythmbox")
RHYTHMBOX_ACTIVE=$(is_active "rhythmbox")
RHYTHMBOX_STATUS=$(status "rhythmbox")
RHYTHMBOX_PLAYING=$(is_playing "rhythmbox")
SPOTIFY_RUNNING=$(is_running "spotify")
SPOTIFY_PLAYING=$(is_playing "spotify")

ARG=$1

function color {
  if [ "$ARG" == "--i3status" ]; then
    echo ""
    echo $1
  fi
}


function tag_start {
  if [ "$ARG" == "--swaystatus" ]; then
    echo "<span foreground=\"$1\">"
  fi
}

function tag_end {
  if [ "$ARG" == "--swaystatus" ]; then
    echo "</span>"
  fi
}

function print_icon {
  if [ "$ARG" == "--i3status" ] || [ "$ARG" == "--swaystatus" ]; then
    if [ "$RHYTHMBOX_RUNNING" == 0 ] && [ "$RHYTHMBOX_ACTIVE" == 0 ] && ([ "$SPOTIFY_PLAYING" != 0 ] || [ "$RHYTHMBOX_PLAYING" == 0 ]); then
      echo -n $RHYTHMBOX_STATUS
    elif [ "$SPOTIFY_RUNNING" == 0 ]; then
      echo -n ""
    else
      exit 0
    fi
    if [ "$ARG" == "--i3status" ]; then
      echo -n "         "
    else
      echo -n "    "
    fi
  fi
}

if [ -z "$ARG" ] || [ "$ARG" == "--help" ]; then
  show_help
  exit 0
fi

if [ "$ARG" == "--status" ] || [ "$ARG" == "--i3status" ] || [ "$ARG" == "--swaystatus" ]; then
  if [ "$RHYTHMBOX_RUNNING" == 0 ] && [ "$RHYTHMBOX_ACTIVE" == 0 ] && ([ "$SPOTIFY_PLAYING" != 0 ] || [ "$RHYTHMBOX_PLAYING" == 0 ]); then
    tag_start "#feb206"
  else
    tag_start "#1db954"
  fi
  print_icon
  if [ "$RHYTHMBOX_RUNNING" == 0 ] && [ "$RHYTHMBOX_ACTIVE" == 0 ] && ([ "$SPOTIFY_PLAYING" != 0 ] || [ "$RHYTHMBOX_PLAYING" == 0 ]); then
    echo $(playing "rhythmbox" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g')
    color "#feb206"
  else
    echo $(playing "spotify" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g')
    color "#1db954"
  fi
  tag_end
elif [ "$ARG" == "--playpause" ]; then
 if [ "$RHYTHMBOX_RUNNING" == 0 ] || [ "$RHYTHMBOX_ACTIVE" == 0 ] && [ "$SPOTIFY_PLAYING" != 0 ]; then
    play_pause "rhythmbox"
  else
    play_pause "spotify"
  fi
else
  echo "Unknown option:"
  echo ""
  show_help
fi
